<?php
/* {[The file is published on the basis of YetiForce Public License that can be found in the following directory: licenses/License.html]} */
$languageStrings = [
	'LBL_ID_CLIENT' => 'Client ID',
	'LBL_TOKEN' => 'Token',
	'LBL_NOT_AUTHORIZED' => 'Authorization required to access all module features.',
	'LBL_TITLE' => 'Title', 
	'LBL_AUTHOR' => 'Author',
	'LBL_ADD_ISSUES' => 'Add',
	'LBL_ADD_ISSUE' => 'New issue',
	'LBL_CLOSED' => 'Closed',
	'LBL_OPEN' => 'Open',
	'LBL_ME' => 'Only me',
	'LBL_ERROR_CONNECTED' => 'Internet connection problems',
	'LBL_CONFIRM_REGULATIONS' => 'I have read the rules of adding new issues: <a href="https://yetiforce.com/en/developer-documentation/bugs/126-issues.html">link</a>',
	'LBL_DEFAULT_DESCRIPTION' => 'Generated by YetiforceCRM ver. ',
	'LBL_CHANGE_AUTHORIZATION' => 'Change authorization',
	'LBL_PHP_VERSION' => 'PHP',
	'LBL_LIBRARIES_ERROR' => 'Library errors',
	'LBL_CONFIGURATION_ERROR' => 'Server configuration errors',
];
