<?php
/**
 * Github german translation
 * @package YetiForce.Language
 * @copyright YetiForce Sp. z o.o.
 * @license YetiForce Public License 3.0 (licenses/LicenseEN.txt or yetiforce.com)
 * @author skavenkf (K.Fink)
 */
$languageStrings = [
	'LBL_TOKEN' => 'Token',
	'LBL_NOT_AUTHORIZED' => 'Authorization required to access all module features.',
	'LBL_TITLE' => 'Titel',
	'LBL_AUTHOR' => 'Author',
	'LBL_ADD_ISSUES' => 'Hinzufügen',
	'LBL_TITLE_ADD_ISSUE' => 'Hinzufügen',
	'LBL_ADD_ISSUE' => 'Neue Meldung',
	'LBL_CLOSED' => 'Geschlossen',
	'LBL_OPEN' => 'Offen',
	'closed' => 'Geschlossen',
	'open' => 'Offen',
	'LBL_ME' => 'Nur für mich',
	'LBL_ERROR_CONNECTED' => 'An error occurred when connecting to  www.api.github.com, check your Internet connection and firewall settings',
	'LBL_CONFIRM_REGULATIONS' => 'I have read the rules of adding new issues: <a href="https://yetiforce.com/en/developer-documentation/bugs/126-issues.html">link</a>',
	'LBL_DEFAULT_DESCRIPTION' => 'Generated by YetiforceCRM ver. ',
	'LBL_CHANGE_AUTHORIZATION' => 'Change authorization',
	'LBL_USERNAME_DESCRIPTION' => 'Your www.github.com username',
	'LBL_TOKEN_DESCRIPTION' => '40 character long unique account access code. Token creation manual can be found <a href="https://help.github.com/articles/creating-an-access-token-for-command-line-use/">here</a>',
	'LBL_NO_ISSUES' => 'Kein gemeldeter Fehler',
	'LBL_PHP_VERSION' => 'PHP',
	'LBL_LIBRARIES_ERROR' => 'Library Fehler',
	'LBL_CONFIGURATION_ERROR' => 'Server Konfigurationsfehler',
];
