<?php

function build_users() {
  $vtiger_users = array(
    array(
      "user_name" => "admin",
      "id" => 1,
      "last_name" => "Administrator",
      "first_name" => "",
      "alias" => "",
    ),
    array(
      "user_name" => "nnau",
      "id" => 18,
      "last_name" => "Aupelt",
      "first_name" => "",
      "alias" => "",
    ),
    array(
      "user_name" => "diba",
      "id" => 19,
      "last_name" => "Backes",
      "first_name" => "Dieter",
      "alias" => "",
    ),
    array(
      "user_name" => "anbl",
      "id" => 20,
      "last_name" => "Bliewert",
      "first_name" => "Andreas",
      "alias" => "",
    ),
    array(
      "user_name" => "nibo",
      "id" => 17,
      "last_name" => "Boll",
      "first_name" => "Nico",
      "alias" => "",
    ),
    array(
      "user_name" => "mabo",
      "id" => 21,
      "last_name" => "Borrmann",
      "first_name" => "Marcel",
      "alias" => "",
    ),
    array(
      "user_name" => "wobu",
      "id" => 22,
      "last_name" => "Busch",
      "first_name" => "Wolfgang",
      "alias" => "",
    ),
    array(
      "user_name" => "sada",
      "id" => 23,
      "last_name" => "Damm",
      "first_name" => "Sascha",
      "alias" => "",
    ),
    array(
      "user_name" => "thdo",
      "id" => 24,
      "last_name" => "Dollmann",
      "first_name" => "Thiemo",
      "alias" => "",
    ),
    array(
      "user_name" => "mado",
      "id" => 25,
      "last_name" => "Domann",
      "first_name" => "Marius",
      "alias" => "",
    ),
    array(
      "user_name" => "jodr",
      "id" => 26,
      "last_name" => "Draudt",
      "first_name" => "Jörg",
      "alias" => "",
    ),
    array(
      "user_name" => "anfa",
      "id" => 27,
      "last_name" => "Fank",
      "first_name" => "Andreas",
      "alias" => "",
    ),
    array(
      "user_name" => "mafe",
      "id" => 28,
      "last_name" => "Fehrentz",
      "first_name" => "Marcel",
      "alias" => "",
    ),
    array(
      "user_name" => "sufi",
      "id" => 29,
      "last_name" => "Fischer",
      "first_name" => "Susanne",
      "alias" => "",
    ),
    array(
      "user_name" => "nifi",
      "id" => 62,
      "last_name" => "Fischer",
      "first_name" => "Nicole",
      "alias" => "N.Fischer",
    ),
    array(
      "user_name" => "befo",
      "id" => 10,
      "last_name" => "Foersterling",
      "first_name" => "Bernd",
      "alias" => "",
    ),
    array(
      "user_name" => "tofr",
      "id" => 30,
      "last_name" => "Franzke",
      "first_name" => "Tom",
      "alias" => "",
    ),
    array(
      "user_name" => "lifr",
      "id" => 31,
      "last_name" => "Frühwein",
      "first_name" => "Lisa",
      "alias" => "",
    ),
    array(
      "user_name" => "anga",
      "id" => 32,
      "last_name" => "Gaul",
      "first_name" => "Angela",
      "alias" => "",
    ),
    array(
      "user_name" => "pagi",
      "id" => 33,
      "last_name" => "Gilcher",
      "first_name" => "Patrick",
      "alias" => "",
    ),
    array(
      "user_name" => "uwgo",
      "id" => 34,
      "last_name" => "Gottsleben",
      "first_name" => "Uwe",
      "alias" => "",
    ),
    array(
      "user_name" => "mihe",
      "id" => 7,
      "last_name" => "Hengen",
      "first_name" => "Michael",
      "alias" => "",
    ),
    array(
      "user_name" => "nnhe",
      "id" => 35,
      "last_name" => "Henrich",
      "first_name" => "",
      "alias" => "",
    ),
    array(
      "user_name" => "mihs",
      "id" => 36,
      "last_name" => "Heß",
      "first_name" => "Michael",
      "alias" => "",
    ),
    array(
      "user_name" => "uwhi",
      "id" => 37,
      "last_name" => "Hiss",
      "first_name" => "Uwe",
      "alias" => "",
    ),
    array(
      "user_name" => "nnho",
      "id" => 38,
      "last_name" => "Hoffmann",
      "first_name" => "",
      "alias" => "",
    ),
    array(
      "user_name" => "paho",
      "id" => 39,
      "last_name" => "Hourticolon",
      "first_name" => "Patrick",
      "alias" => "",
    ),
    array(
      "user_name" => "diim",
      "id" => 40,
      "last_name" => "Imandt",
      "first_name" => "Dirk",
      "alias" => "",
    ),
    array(
      "user_name" => "svja",
      "id" => 41,
      "last_name" => "Jäckel",
      "first_name" => "Sven",
      "alias" => "",
    ),
    array(
      "user_name" => "elja",
      "id" => 42,
      "last_name" => "Jakobi",
      "first_name" => "Elena",
      "alias" => "",
    ),
    array(
      "user_name" => "nnja",
      "id" => 43,
      "last_name" => "Jakubowski",
      "first_name" => "",
      "alias" => "",
    ),
    array(
      "user_name" => "hajo",
      "id" => 44,
      "last_name" => "Jochum",
      "first_name" => "",
      "alias" => "",
    ),
    array(
      "user_name" => "olju",
      "id" => 45,
      "last_name" => "Jung",
      "first_name" => "Olaf",
      "alias" => "",
    ),
    array(
      "user_name" => "maju",
      "id" => 46,
      "last_name" => "JungMax",
      "first_name" => "Maximilian",
      "alias" => "JungM",
    ),
    array(
      "user_name" => "maka",
      "id" => 8,
      "last_name" => "Kartes",
      "first_name" => "Manuel",
      "alias" => "",
    ),
    array(
      "user_name" => "jake",
      "id" => 47,
      "last_name" => "Kehl",
      "first_name" => "Janos",
      "alias" => "",
    ),
    array(
      "user_name" => "flke",
      "id" => 48,
      "last_name" => "Kern",
      "first_name" => "Florian",
      "alias" => "",
    ),
    array(
      "user_name" => "chki",
      "id" => 49,
      "last_name" => "Kisch",
      "first_name" => "Christian",
      "alias" => "",
    ),
    array(
      "user_name" => "pakn",
      "id" => 50,
      "last_name" => "Knobloch",
      "first_name" => "Paul",
      "alias" => "",
    ),
    array(
      "user_name" => "mako",
      "id" => 51,
      "last_name" => "König",
      "first_name" => "Markus",
      "alias" => "",
    ),
    array(
      "user_name" => "sako",
      "id" => 52,
      "last_name" => "Kontic",
      "first_name" => "Sascha",
      "alias" => "",
    ),
    array(
      "user_name" => "reko",
      "id" => 53,
      "last_name" => "Kopp",
      "first_name" => "Rene",
      "alias" => "",
    ),
    array(
      "user_name" => "makr",
      "id" => 54,
      "last_name" => "Kratz",
      "first_name" => "Maximilian",
      "alias" => "",
    ),
    array(
      "user_name" => "silo",
      "id" => 55,
      "last_name" => "Louis",
      "first_name" => "Simone",
      "alias" => "",
    ),
    array(
      "user_name" => "mama",
      "id" => 56,
      "last_name" => "Magold",
      "first_name" => "Markus",
      "alias" => "",
    ),
    array(
      "user_name" => "nnm1",
      "id" => 57,
      "last_name" => "Marketing01",
      "first_name" => "",
      "alias" => "",
    ),
    array(
      "user_name" => "nnm2",
      "id" => 58,
      "last_name" => "Marketing02",
      "first_name" => "",
      "alias" => "",
    ),
    array(
      "user_name" => "nnmi",
      "id" => 59,
      "last_name" => "Mink",
      "first_name" => "",
      "alias" => "",
    ),
    array(
      "user_name" => "nnmo",
      "id" => 60,
      "last_name" => "Moosler",
      "first_name" => "",
      "alias" => "",
    ),
    array(
      "user_name" => "nnmu",
      "id" => 61,
      "last_name" => "Müller",
      "first_name" => "",
      "alias" => "",
    ),
    array(
      "user_name" => "nnop",
      "id" => 63,
      "last_name" => "OP",
      "first_name" => "",
      "alias" => "",
    ),
    array(
      "user_name" => "nnot",
      "id" => 64,
      "last_name" => "Otto",
      "first_name" => "",
      "alias" => "",
    ),
    array(
      "user_name" => "meoe",
      "id" => 65,
      "last_name" => "Özkan",
      "first_name" => "Merve",
      "alias" => "",
    ),
    array(
      "user_name" => "kapa",
      "id" => 66,
      "last_name" => "Patzelt",
      "first_name" => "Katherina",
      "alias" => "",
    ),
    array(
      "user_name" => "chpa",
      "id" => 67,
      "last_name" => "Pauli",
      "first_name" => "Christian",
      "alias" => "",
    ),
    array(
      "user_name" => "rupe",
      "id" => 68,
      "last_name" => "Paulsen",
      "first_name" => "Ruth",
      "alias" => "",
    ),
    array(
      "user_name" => "rupa",
      "id" => 69,
      "last_name" => "Paulus",
      "first_name" => "Ruth",
      "alias" => "paulus",
    ),
    array(
      "user_name" => "nnpe",
      "id" => 70,
      "last_name" => "Petry",
      "first_name" => "",
      "alias" => "",
    ),
    array(
      "user_name" => "depo",
      "id" => 71,
      "last_name" => "Porth",
      "first_name" => "Dennis",
      "alias" => "",
    ),
    array(
      "user_name" => "nnpo",
      "id" => 72,
      "last_name" => "ProCRM",
      "first_name" => "",
      "alias" => "",
    ),
    array(
      "user_name" => "dare",
      "id" => 6,
      "last_name" => "Reischmann",
      "first_name" => "Daniel",
      "alias" => "",
    ),
    array(
      "user_name" => "stri",
      "id" => 73,
      "last_name" => "Riek",
      "first_name" => "Stefanie",
      "alias" => "",
    ),
    array(
      "user_name" => "anro",
      "id" => 74,
      "last_name" => "RöderA",
      "first_name" => "Andreas",
      "alias" => "",
    ),
    array(
      "user_name" => "tharo",
      "id" => 75,
      "last_name" => "RöderT",
      "first_name" => "Tanja",
      "alias" => "",
    ),
    array(
      "user_name" => "nnsa",
      "id" => 76,
      "last_name" => "Saliew",
      "first_name" => "",
      "alias" => "",
    ),
    array(
      "user_name" => "disc",
      "id" => 80,
      "last_name" => "Schoeffler",
      "first_name" => "Dietmar",
      "alias" => "Schöffler",
    ),
    array(
      "user_name" => "thsc",
      "id" => 77,
      "last_name" => "Schäfer",
      "first_name" => "Thomas",
      "alias" => "",
    ),
    array(
      "user_name" => "nnsc",
      "id" => 78,
      "last_name" => "Schauf",
      "first_name" => "",
      "alias" => "",
    ),
    array(
      "user_name" => "nisc",
      "id" => 79,
      "last_name" => "Schilling",
      "first_name" => "Niclas",
      "alias" => "",
    ),
    array(
      "user_name" => "kesc",
      "id" => 16,
      "last_name" => "Schlemmer",
      "first_name" => "Kevin",
      "alias" => "",
    ),
    array(
      "user_name" => "nnsu",
      "id" => 81,
      "last_name" => "Schunck",
      "first_name" => "",
      "alias" => "",
    ),
    array(
      "user_name" => "wesc",
      "id" => 82,
      "last_name" => "Schwab",
      "first_name" => "Werner",
      "alias" => "",
    ),
    array(
      "user_name" => "jost",
      "id" => 83,
      "last_name" => "Staske",
      "first_name" => "Jörg",
      "alias" => "",
    ),
    array(
      "user_name" => "Support",
      "id" => 13,
      "last_name" => "Support",
      "first_name" => "",
      "alias" => "",
    ),
    array(
      "user_name" => "batr",
      "id" => 84,
      "last_name" => "Triebel",
      "first_name" => "Baerbel",
      "alias" => "",
    ),
    array(
      "user_name" => "unbekannt",
      "id" => 15,
      "last_name" => "Unbekannt",
      "first_name" => "",
      "alias" => "",
    ),
    array(
      "user_name" => "atva",
      "id" => 85,
      "last_name" => "Vaskoskyy",
      "first_name" => "Artem",
      "alias" => "",
    ),
    array(
      "user_name" => "mavi",
      "id" => 86,
      "last_name" => "Viehweger",
      "first_name" => "Martin",
      "alias" => "",
    ),
    array(
      "user_name" => "mavo",
      "id" => 87,
      "last_name" => "Volz",
      "first_name" => "Maximilian",
      "alias" => "",
    ),
    array(
      "user_name" => "vawa",
      "id" => 88,
      "last_name" => "Walch",
      "first_name" => "Vanessa",
      "alias" => "walch",
    ),
    array(
      "user_name" => "mowa",
      "id" => 89,
      "last_name" => "Wallat",
      "first_name" => "Monika",
      "alias" => "",
    ),
    array(
      "user_name" => "lewa",
      "id" => 90,
      "last_name" => "Wassermann",
      "first_name" => "Leonie",
      "alias" => "",
    ),
    array(
      "user_name" => "alwe",
      "id" => 5,
      "last_name" => "Weber",
      "first_name" => "Alexander",
      "alias" => "",
    ),
    array(
      "user_name" => "yawe",
      "id" => 91,
      "last_name" => "Weyand",
      "first_name" => "Yannick",
      "alias" => "",
    ),
    array(
      "user_name" => "Wilhelm",
      "id" => 9,
      "last_name" => "Wilhelm",
      "first_name" => "Benjamin",
      "alias" => "",
    ),
    array(
      "user_name" => "jixu",
      "id" => 92,
      "last_name" => "Xu",
      "first_name" => "Jianda",
      "alias" => "",
    ),
    array(
      "user_name" => "frzi",
      "id" => 93,
      "last_name" => "Zimmermann",
      "first_name" => "Frank",
      "alias" => "",
    ),
  );
  $users = array();
  foreach($vtiger_users as $user) {
    $users[$user['last_name']] = $user;
    if (!empty($user['alias'])) {
      $users[$user['alias']] = $user;
    }
  }

  return $users;
}


?>