<?php

return [
	'Administration',
	'Construction Industry',
	'Education',
	'Power Industry',
	'Finance',
	'Trade',
	'Hotels and Restaurants',
	'Health Care',
	'Industry / Manufacturing',
	'Uniformed Services',
	'Transport & Logistics',
	'Technologies',
	'Ministry',
	'Chancellery',
	'Voivodeship Office',
	'Marshal Office',
	'District',
	'City/Township/District',
	'Social Welfare Centre',
	'Water and Sewerage Company',
	'Voivodeship Job Centre',
	'District Job Center',
	'Court of justice',
	'Attorney General\'s Office',
	'Developers',
	'Real Estate',
	'Primary Schools',
	'High Schools',
	'Banking',
	'Capital Market',
	'Financial Services',
	'Investments',
	'Insurance',
	'Retail',
	'Wholesale',
	'Resale',
	'Automotive',
	'Plastics',
	'Chamical',
	'Raw material',
	'Fuel',
	'Wood and paper',
	'Electromechanical',
	'Pharmaceutical',
	'Building Materials',
	'Metal',
	'Light',
	'Food industry',
	'Recycling',
	'Army',
	'Police',
	'Information Technology',
	'Telecommunication',
	'Media',
	'Other',
];
