<?php

// autoload_psr4.php @generated by Composer

$baseDir = dirname(dirname(__FILE__));

return array(
    'Sabre\\VObject\\' => array($baseDir . '/VObject'),
    'Sabre\\HTTP\\' => array($baseDir . '/HTTP'),
    'Sabre\\Event\\' => array($baseDir . '/Event'),
    'Sabre\\DAV\\' => array($baseDir . '/DAV'),
    'Sabre\\DAVACL\\' => array($baseDir . '/DAVACL'),
    'Sabre\\CardDAV\\' => array($baseDir . '/CardDAV'),
    'Sabre\\CalDAV\\' => array($baseDir . '/CalDAV'),
	'Yeti\\' => array($baseDir . '/Yeti'),
);
