<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return [
	'Sabre\\Xml\\' => [$vendorDir . '/Xml'],
	'Sabre\\VObject\\' => [$vendorDir . '/VObject'],
	'Sabre\\Uri\\' => [$vendorDir . '/Uri'],
	'Sabre\\HTTP\\' => [$vendorDir . '/HTTP'],
	'Sabre\\Event\\' => [$vendorDir . '/Event'],
	'Sabre\\DAV\\' => [$vendorDir . '/DAV'],
	'Sabre\\DAVACL\\' => [$vendorDir . '/DAVACL'],
	'Sabre\\CardDAV\\' => [$vendorDir . '/CardDAV'],
	'Sabre\\CalDAV\\' => [$vendorDir . '/CalDAV'],
	'Yeti\\' => [$vendorDir . '/Yeti'],
];
