<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return [
	'383eaff206634a77a1be54e64e6459c7' => $vendorDir . '/Uri/functions.php',
	'2b9d0f43f9552984cfa82fee95491826' => $vendorDir . '/Event/coroutine.php',
	'd81bab31d3feb45bfe2f283ea3c8fdf7' => $vendorDir . '/Event/Loop/functions.php',
	'a1cce3d26cc15c00fcd0b3354bd72c88' => $vendorDir . '/Event/Promise/functions.php',
	'3569eecfeed3bcf0bad3c998a494ecb8' => $vendorDir . '/Xml/Deserializer/functions.php',
	'93aa591bc4ca510c520999e34229ee79' => $vendorDir . '/Xml/Serializer/functions.php',
	'ebdb698ed4152ae445614b69b5e4bb6a' => $vendorDir . '/HTTP/functions.php',
];
