DROP TABLE IF EXISTS `vtiger_crmsetup`;
DROP TABLE IF EXISTS `vtiger_emailtemplates`;
DROP TABLE IF EXISTS `vtiger_emailtemplates_seq`;
DROP TABLE IF EXISTS `vtiger_extnstore_users`;
DROP TABLE IF EXISTS `vtiger_inventoryshippingrel`;
DROP TABLE IF EXISTS `vtiger_invoicebillads`;
DROP TABLE IF EXISTS `vtiger_invoiceshipads`;
DROP TABLE IF EXISTS `vtiger_mailmanager_mailattachments`;
DROP TABLE IF EXISTS `vtiger_mailmanager_mailrecord`;
DROP TABLE IF EXISTS `vtiger_mailmanager_mailrel`;
DROP TABLE IF EXISTS `vtiger_mailscanner`;
DROP TABLE IF EXISTS `vtiger_mailscanner_actions`;
DROP TABLE IF EXISTS `vtiger_mailscanner_folders`;
DROP TABLE IF EXISTS `vtiger_mailscanner_ids`;
DROP TABLE IF EXISTS `vtiger_mailscanner_ruleactions`;
DROP TABLE IF EXISTS `vtiger_mailscanner_rules`;
DROP TABLE IF EXISTS `vtiger_notificationscheduler`;
DROP TABLE IF EXISTS `vtiger_notificationscheduler_seq`;
DROP TABLE IF EXISTS `vtiger_parenttabrel`;
DROP TABLE IF EXISTS `vtiger_parenttab`;
DROP TABLE IF EXISTS `vtiger_pobillads`;
DROP TABLE IF EXISTS `vtiger_poshipads`;
DROP TABLE IF EXISTS `vtiger_quotesbillads`;
DROP TABLE IF EXISTS `vtiger_quotesshipads`;
DROP TABLE IF EXISTS `vtiger_attachmentsfolder`;
DROP TABLE IF EXISTS `vtiger_attachmentsfolder_seq`;
-- DROP TABLE IF EXISTS `vtiger_rating`;
-- DROP TABLE IF EXISTS `vtiger_rating_seq`;
DROP TABLE IF EXISTS `vtiger_shippingtaxinfo`;
DROP TABLE IF EXISTS `vtiger_shippingtaxinfo_seq`;
DROP TABLE IF EXISTS `vtiger_sobillads`;
DROP TABLE IF EXISTS `vtiger_soshipads`;
DROP TABLE IF EXISTS `vtiger_accountbillads`;
DROP TABLE IF EXISTS `vtiger_accountshipads`;
DROP TABLE IF EXISTS `vtiger_google_oauth2`;
DROP TABLE IF EXISTS `vtiger_google_sync_fieldmapping`;
DROP TABLE IF EXISTS `vtiger_google_sync_settings`;

	
-- DELETE FROM vtiger_settings_field WHERE =?';