<?php

$labels = array();
$labels['smtp_settings_header'] = 'SMTP Einstellungen';
$labels['use_default_smtp_server'] = 'Den voreingestellten SMTP Server verwenden';
$labels['smtp_server'] = 'Server IP/Hostname';
$labels['smtp_port'] = 'Server Port';
$labels['smtp_user'] = 'Benutzername';
$labels['smtp_pass'] = 'Passwort';
$labels['smtp_settings_not_available'] = 'Bitte erst speichern, bevor die SMTP Einstellungen vorgenommen werden können.';

?>
