openapi: 3.0.0
info:
  title: 'YetiForce API for Webservice App. Type: Mail'
  termsOfService: 'https://yetiforce.com/'
  contact:
    name: 'Devs API Team'
    url: 'https://yetiforce.com/'
    email: devs@yetiforce.com
  license:
    name: 'YetiForce Public License v3'
    url: 'https://yetiforce.com/en/yetiforce/license'
  version: '0.1'
paths:
  /webservice/Install:
    put:
      tags:
        - BaseAction
      summary: 'Action to check configuration and API connection test'
      operationId: 'Api\Mail\BaseAction\Install::put'
      parameters:
        -
          name: X-ENCRYPTED
          in: header
          required: true
          schema:
            $ref: '#/components/schemas/X-ENCRYPTED'
      requestBody:
        description: 'Content of the request'
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/InstallRequestBody'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/InstallRequestBody'
          application/json:
            schema:
              $ref: '#/components/schemas/InstallRequestBody'
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InstallResponseBody'
        '401':
          description: 'Invalid api key'
        '405':
          description: 'Invalid method'
      security:
        -
          basicAuth: ''
          ApiKeyAuth: ''
  /webservice/Users/Login:
    post:
      tags:
        - Users
      summary: 'Logs user into the system'
      operationId: 'Api\Mail\Users\Login::post'
      parameters:
        -
          name: X-ENCRYPTED
          in: header
          required: true
          schema:
            $ref: '#/components/schemas/X-ENCRYPTED'
      requestBody:
        description: 'Input data format'
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UsersLoginRequestBody'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UsersLoginRequestBody'
          application/json:
            schema:
              $ref: '#/components/schemas/UsersLoginRequestBody'
      responses:
        '200':
          description: 'User details'
          content:
            text/html:
              schema:
                $ref: '#/components/schemas/UsersLoginResponseBody'
            application/json:
              schema:
                $ref: '#/components/schemas/UsersLoginResponseBody'
            application/xml:
              schema:
                $ref: '#/components/schemas/UsersLoginResponseBody'
        '401':
          description: 'Invalid data access OR Invalid user password OR No crmid'
        '405':
          description: 'Invalid method'
      security:
        -
          basicAuth: ''
          ApiKeyAuth: ''
components:
  schemas:
    X-ENCRYPTED:
      description: 'Is the content request is encrypted'
      type: string
      default: '0'
      enum:
        - '0'
        - '1'
    InstallRequestBody:
      title: 'Install request body'
      description: 'The body content is optional, if it is sent then the API will send it in response'
      type: object
    InstallResponseBody:
      title: 'Install response body'
      description: 'JSON data'
      properties:
        status:
          description: 'A numeric value of 0 or 1 that indicates whether the communication is valid. 1 - sukcess , 0 - error'
          type: integer
          enum:
            - '0'
            - '1'
        result:
          description: 'Content of responses from a given method'
          properties:
            serverTime:
              title: 'current time on the server'
              description: 'Put method.'
              type: string
              format: date-time
              example: '2019-10-09 11:41:40'
            tokenExist:
              title: 'Does the token exist in the header?'
              description: 'Put method.'
              type: boolean
            apiKey:
              title: 'api key sent in header'
              description: 'Put method.'
              type: string
            data:
              title: 'Data that was sent in the request'
              description: 'Put method.'
              type: object
          type: object
      type: object
    UsersLoginRequestBody:
      title: 'Users login request body'
      description: 'JSON or form-data'
      properties:
        userName:
          description: 'Webservice user name'
          type: string
        password:
          description: 'Webservice user password'
          type: string
        params:
          description: 'Additional parameters sent by the user, extending the current settings, e.g. language'
          type: array
          items:
            type: string
      type: object
    UsersLoginResponseBody:
      title: 'Users login response body'
      description: 'JSON data'
      properties:
        status:
          description: 'A numeric value of 0 or 1 that indicates whether the communication is valid. 1 - sukcess , 0 - error'
          type: integer
          enum:
            - '0'
            - '1'
        result:
          description: 'Content of responses from a given method'
          properties:
            token:
              description: 'Post method.'
              type: string
              maxLength: 40
              minLength: 40
            name:
              description: 'Post method.'
              type: string
            parentName:
              description: 'Post method.'
              type: string
            lastLoginTime:
              description: 'Post method.'
              type: string
              format: date-time
              example: '2019-10-07 08:32:38'
            lastLogoutTime:
              description: 'Post method.'
              type: string
              format: date-time
              example: 'null'
            language:
              description: 'Post method.'
              type: string
              example: pl-PL
            type:
              description: 'Post method.'
              type: integer
            companyId:
              description: 'Post method.'
              type: integer
            companyDetails:
              description: 'Post method.'
              type: array
              items:
                type: string
            logged:
              description: 'Post method.'
              type: boolean
            preferences:
              description: 'Post method.'
              properties:
                activity_view:
                  description: 'Post method.'
                  type: string
                hour_format:
                  description: 'Post method.'
                  type: integer
                start_hour:
                  description: 'Post method.'
                  type: string
                date_format:
                  description: 'Post method.'
                  type: string
                date_format_js:
                  description: 'Post method.'
                  type: string
                dayoftheweek:
                  description: 'Post method.'
                  type: string
                time_zone:
                  description: 'Post method.'
                  type: string
                currency_id:
                  description: 'Post method.'
                  type: integer
                currency_grouping_pattern:
                  description: 'Post method.'
                  type: string
                currency_decimal_separator:
                  description: 'Post method.'
                  type: string
                currency_grouping_separator:
                  description: 'Post method.'
                  type: string
                currency_symbol_placement:
                  description: 'Post method.'
                  type: string
                no_of_currency_decimals:
                  description: 'Post method.'
                  type: integer
                truncate_trailing_zeros:
                  description: 'Post method.'
                  type: integer
                end_hour:
                  description: 'Post method.'
                  type: string
                currency_name:
                  description: 'Post method.'
                  type: string
                currency_code:
                  description: 'Post method.'
                  type: string
                currency_symbol:
                  description: 'Post method.'
                  type: string
                conv_rate:
                  description: 'Post method.'
                  type: number
                  format: float
              type: object
          type: object
      type: object
  securitySchemes:
    basicAuth:
      type: http
      in: header
      scheme: basic
    ApiKeyAuth:
      type: apiKey
      description: 'Webservice api key'
      name: X-API-KEY
      in: header
tags:
  -
    name: BaseAction
    description: 'Basic Webservice API methods'
  -
    name: Users
    description: 'Access to user methods'
