openapi: 3.0.0
info:
  title: 'YetiForce API for Webservice App. Type: Portal'
  termsOfService: 'https://yetiforce.com/'
  contact:
    name: 'Devs API Team'
    url: 'https://yetiforce.com/'
    email: devs@yetiforce.com
  license:
    name: 'YetiForce Public License v3'
    url: 'https://yetiforce.com/en/yetiforce/license'
  version: '0.1'
paths:
  /webservice/Install:
    put:
      tags:
        - BaseAction
      summary: 'Install the system'
      operationId: 'Api\Portal\BaseAction\Install::put'
      parameters:
        -
          name: X-ENCRYPTED
          in: header
          required: true
          schema:
            $ref: '#/components/schemas/X-ENCRYPTED'
      requestBody:
        description: 'Base action install request body'
        required: false
      responses:
        '200':
          description: 'Base action details'
          content:
            text/html:
              schema:
                $ref: '#/components/schemas/BaseActionInstallResponseBody'
            application/json:
              schema:
                $ref: '#/components/schemas/BaseActionInstallResponseBody'
            application/xml:
              schema:
                $ref: '#/components/schemas/BaseActionInstallResponseBody'
      security:
        -
          basicAuth: ''
          ApiKeyAuth: ''
  /webservice/Modules:
    get:
      tags:
        - BaseAction
      summary: 'Gets the module list action, along with their translated action'
      operationId: 'Api\Portal\BaseAction\Modules::get'
      parameters:
        -
          name: X-ENCRYPTED
          in: header
          required: true
          schema:
            $ref: '#/components/schemas/X-ENCRYPTED'
      requestBody:
        description: 'The content of the request is empty'
        required: false
      responses:
        '200':
          description: 'List of active modules'
          content:
            text/html:
              schema:
                $ref: '#/components/schemas/BaseActionModulesResponseBody'
            application/json:
              schema:
                $ref: '#/components/schemas/BaseActionModulesResponseBody'
            application/xml:
              schema:
                $ref: '#/components/schemas/BaseActionModulesResponseBody'
        '401':
          description: 'No sent token OR Invalid token'
        '403':
          description: 'No permissions for module'
      security:
        -
          basicAuth: ''
          ApiKeyAuth: ''
          token: ''
  /webservice/Users/Login:
    post:
      tags:
        - Users
      summary: 'Logs user into the system'
      operationId: 'Api\Portal\Users\Login::post'
      parameters:
        -
          name: X-ENCRYPTED
          in: header
          required: true
          schema:
            $ref: '#/components/schemas/X-ENCRYPTED'
      requestBody:
        description: 'Input data format'
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UsersLoginRequestBody'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UsersLoginRequestBody'
          application/json:
            schema:
              $ref: '#/components/schemas/UsersLoginRequestBody'
      responses:
        '200':
          description: 'User details'
          content:
            text/html:
              schema:
                $ref: '#/components/schemas/UsersLoginResponseBody'
            application/json:
              schema:
                $ref: '#/components/schemas/UsersLoginResponseBody'
            application/xml:
              schema:
                $ref: '#/components/schemas/UsersLoginResponseBody'
        '401':
          description: 'Invalid data access OR Invalid user password OR No crmid'
        '405':
          description: 'Invalid method'
      security:
        -
          basicAuth: ''
          ApiKeyAuth: ''
  /webservice/Users/Logout:
    put:
      tags:
        - Users
      summary: 'Logout user out the system'
      operationId: 'Api\Portal\Users\Logout::put'
      parameters:
        -
          name: X-ENCRYPTED
          in: header
          required: true
          schema:
            $ref: '#/components/schemas/X-ENCRYPTED'
      requestBody:
        description: 'Users logout request body'
        required: false
      responses:
        '200':
          description: 'User details'
          content:
            text/html:
              schema:
                $ref: '#/components/schemas/UsersLogoutResponseBody'
            application/json:
              schema:
                $ref: '#/components/schemas/UsersLogoutResponseBody'
            application/xml:
              schema:
                $ref: '#/components/schemas/UsersLogoutResponseBody'
      security:
        -
          basicAuth: ''
          ApiKeyAuth: ''
          token: ''
components:
  schemas:
    BaseActionInstallResponseBody:
      title: 'Base action install'
      description: 'The representation of a base action install'
      properties:
        status:
          description: 'A numeric value of 0 or 1 that indicates whether the communication is valid. 1 - sukcess , 0 - error'
          type: integer
          enum:
            - '0'
            - '1'
        result:
          description: 'Content of responses from a given method'
          type: object
      type: object
    BaseActionModulesResponseBody:
      title: 'List items'
      description: 'List of obtained items'
      properties:
        status:
          description: 'A numeric value of 0 or 1 that indicates whether the communication is valid. 1 - sukcess , 0 - error'
          type: integer
          enum:
            - '0'
            - '1'
        result:
          description: 'List of modules accessed'
          properties:
            items:
              description: 'Module name'
              type: string
              example: Accounts
          type: object
      type: object
    X-ENCRYPTED:
      description: 'Is the content request is encrypted'
      type: string
      default: '0'
      enum:
        - '0'
        - '1'
    UsersLoginRequestBody:
      title: 'Users login request body'
      description: 'JSON or form-data'
      properties:
        userName:
          description: 'Webservice user name'
          type: string
        password:
          description: 'Webservice user password'
          type: string
        params:
          description: 'Additional parameters sent by the user, extending the current settings, e.g. language'
          type: array
          items:
            type: string
      type: object
    UsersLoginResponseBody:
      title: 'Users login response body'
      description: 'Users login response body'
      properties:
        status:
          description: 'A numeric value of 0 or 1 that indicates whether the communication is valid. 1 - sukcess , 0 - error'
          type: integer
          enum:
            - '0'
            - '1'
        result:
          description: 'Content of responses from a given method'
          properties:
            token:
              description: 'Post method.'
              type: string
              maxLength: 40
              minLength: 40
            name:
              description: 'Post method.'
              type: string
            parentName:
              description: 'Post method.'
              type: string
            lastLoginTime:
              description: 'Post method.'
              type: string
              format: date-time
              example: '2019-10-07 08:32:38'
            lastLogoutTime:
              description: 'Post method.'
              type: string
              format: date-time
              example: 'null'
            language:
              description: 'Post method.'
              type: string
              example: pl-PL
            type:
              description: 'Post method.'
              type: integer
            companyId:
              description: 'Post method.'
              type: integer
            companyDetails:
              title: 'Company details, optional parameter depending on the user type'
              description: 'Post method.'
              properties:
                check_stock_levels:
                  description: 'Post method.'
                  type: boolean
                sum_open_orders:
                  description: 'Post method.'
                  type: integer
                creditlimit:
                  description: 'Post method.'
                  type: integer
              type: object
            logged:
              description: 'Post method.'
              type: boolean
            preferences:
              description: 'Post method.'
              properties:
                activity_view:
                  description: 'Post method.'
                  type: string
                hour_format:
                  description: 'Post method.'
                  type: integer
                start_hour:
                  description: 'Post method.'
                  type: string
                date_format:
                  description: 'Post method.'
                  type: string
                date_format_js:
                  description: 'Post method.'
                  type: string
                dayoftheweek:
                  description: 'Post method.'
                  type: string
                time_zone:
                  description: 'Post method.'
                  type: string
                currency_id:
                  description: 'Post method.'
                  type: integer
                currency_grouping_pattern:
                  description: 'Post method.'
                  type: string
                currency_decimal_separator:
                  description: 'Post method.'
                  type: string
                currency_grouping_separator:
                  description: 'Post method.'
                  type: string
                currency_symbol_placement:
                  description: 'Post method.'
                  type: string
                no_of_currency_decimals:
                  description: 'Post method.'
                  type: integer
                truncate_trailing_zeros:
                  description: 'Post method.'
                  type: integer
                end_hour:
                  description: 'Post method.'
                  type: string
                currency_name:
                  description: 'Post method.'
                  type: string
                currency_code:
                  description: 'Post method.'
                  type: string
                currency_symbol:
                  description: 'Post method.'
                  type: string
                conv_rate:
                  description: 'Post method.'
                  type: number
                  format: float
              type: object
          type: object
      type: object
    UsersLogoutResponseBody:
      title: 'Users logout response body'
      description: 'JSON data'
      properties:
        status:
          description: 'A numeric value of 0 or 1 that indicates whether the communication is valid. 1 - sukcess , 0 - error'
          type: integer
          enum:
            - '0'
            - '1'
        result:
          description: 'Content of responses from a given method'
          type: boolean
      type: object
  securitySchemes:
    basicAuth:
      type: http
      in: header
      scheme: basic
    ApiKeyAuth:
      type: apiKey
      description: 'Webservice api key'
      name: X-API-KEY
      in: header
    token:
      type: apiKey
      description: 'Webservice api token, generated when logging into the system, required for communication'
      name: X-TOKEN
      in: header
tags:
  -
    name: BaseAction
    description: 'Access to user methods'
  -
    name: Users
    description: 'Access to user methods'
