<?php
// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return [
	'vtlib\\' => [$baseDir . '/vtlib/Vtiger'],
	'includes\\' => [$baseDir . '/include'],
	'Exception\\' => [$baseDir . '/include/exceptions']
];
