<?php
// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return [
	'vtlib\\' => [$baseDir . '/vtlib/Vtiger'],
	'includes\\' => [$baseDir . '/include'],
	'App\\' => [$baseDir . '/vendor/yetiforce'],
	'Exception\\' => [$baseDir . '/include/exceptions'],
	'DebugBar\\' => [$baseDir . '/libraries/php-debugbar/src/DebugBar'],
	'Symfony\\Component\\VarDumper\\' => [$baseDir . '/libraries/symfony/var-dumper'],
];
