/* {[The file is published on the basis of YetiForce Public License 3.0 that can be found in the following directory: licenses/LicenseEN.txt or yetiforce.com]} */
import ar from 'quasar/lang/ar.js'
import da from 'quasar/lang/da.js'
import de from 'quasar/lang/de.js'
import el from 'quasar/lang/el.js'
import en from 'quasar/lang/en-us.js'
import es from 'quasar/lang/es.js'
import fa from 'quasar/lang/fa-ir.js'
import fr from 'quasar/lang/fr.js'
import it from 'quasar/lang/it.js'
import nl from 'quasar/lang/nl.js'
import pl from 'quasar/lang/pl.js'
import ptBR from 'quasar/lang/pt-br.js'
import ptPT from 'quasar/lang/pt.js'
import ro from 'quasar/lang/ro.js'
import sl from 'quasar/lang/sl.js'
import tr from 'quasar/lang/tr.js'
import uk from 'quasar/lang/uk.js'
import zh from 'quasar/lang/zh-hans.js'

export default { ar, da, de, el, en, es, fa, fr, it, nl, pl, ptBR, ptPT, ro, sl, tr, uk, zh }
