<?php
/* {[The file is published on the basis of YetiForce Public License that can be found in the following directory: licenses/License.html]} */
$languageStrings = [
	'LBL_ID_CLIENT' => 'ID klienta',
	'LBL_TOKEN' => 'Token',
	'LBL_NOT_AUTHORIZED' => 'By w pełni korzystać z możliwości modułu prosimy o autoryzację',
	'LBL_TITLE' => 'Tytuł', 
	'LBL_AUTHOR' => 'Autor',
	'LBL_ADD_ISSUES' => 'Dodaj',
	'LBL_ADD_ISSUE' => 'Dodaj problem',
	'LBL_CLOSED' => 'Zamknięte',
	'LBL_OPEN' => 'Otwarte',
	'LBL_ME' => 'Tylko ja',
	'LBL_ERROR_CONNECTED' => 'Błąd z połączeniem do internetu',
	'LBL_CONFIRM_REGULATIONS' => 'Zapoznałem się z regulaminem dodawania problemów',
	'LBL_DEFAULT_DESCRIPTION' => 'Generated by YetiforceCRM ver. ',
	'LBL_CHANGE_AUTHORIZATION' => 'Zmień autoryzację',
];
